######################################################################
# Automatically generated by qmake (2.01a) Tue Aug 6 12:48:44 2013
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += DataBuffer.h
SOURCES += DataBuffer.cpp main.cpp
LIBS += -lcrypto
